

POST https://localhost:44301/api/utilisateurs/6/groupes?monnaie=0&nom=testegdfgf
Content-Type: application/xml

###
PUT http://localhost:8080/api/utilisateurs/modifier/10
Content-Type: application/json

{
  "Nom": "julien j",
  "Courriel": "jj@jde.com",
  "Monnaie": "CAD",
  "MotDePasse": "julien1234"
  
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
  
  "Courriel": "jj@jde.com",

  "MotDePasse": ""
}


###

PUT http://192.168.0.23:44302/api/factures
Content-Type: application/json

{"DateCreation":"2020-11-11 00:00:00","Id":23,"IdGroupe":0,"UtilisateurCreateurId":10,"PayeursEtMontant":[{"UtilisateurId":10,"MontantPaye":54444.0}],"dateFacture":{},"Nom":"Facture du 2020-11-11","montantPayeParParUtilisateur":{"10":54444.0},"MontantTotal":54444.0}


###
POST http://192.168.0.23:44302/api/login
Content-Type: application/json

{"Courriel":"jj@jde.com","MotDePasse":"julien123"}


###
POST http://localhost:8080/api/utilisateurs/10/groupes?nom=nouveau&monnaie=0
Content-Type: application/json

{
  "Nom": "hvhhhhh", "Monnaie": 0
}

###
PUT https://localhost:44301/api/groupes/1?nom=changed

###
https://localhost:44301/api/utilisateurs/1/groupes/1
Content-Type: application/json

###
POST https://localhost:44301/api/groupes/1?idUtilisateur=2

###
GET https://skillbillweb.azurewebsites.net/api/utilisateurs

###
GET http://192.168.0.23:44302/api/utilisateurs/0/groupes/6

###

GET http://localhost:8080/api/utilisateurs/10/groupes/7
api-key : E422CD9758E1EC2CB8C0B73DB8F993DBE68037CF2832D68C2C483507DF6984332B381361EF5C8B4A3A2089B405042767C63398F37FD34BEE31D0058296B34B40

###
POST http://localhost:8080/api/factures
api-key : E422CD9758E1EC2CB8C0B73DB8F993DBE68037CF2832D68C2C483507DF6984332B381361EF5C8B4A3A2089B405042767C63398F37FD34BEE31D0058296B34B40
Content-Type: application/json

{
  "PayeursEtMontant": [
    {
      "UtilisateurId": 10,
      "MontantPaye": 2.1
    }
  ],
  "UtilisateurCreateurId": 10,
  "DateCreation": "2020-01-01",
  "MontantTotal": 2.1,
  "Nom": "sample string 5",
  "IdGroupe": 7
}

###

POST  http://localhost:8080//api/factures
Content-Type: application/json
Accept: application/xml

  {
    "Photos": null,
    "PayeursEtMontant": [
      {
        "UtilisateurId": 1,
        "MontantPaye": 24432.3
      },
      {
        "UtilisateurId": 4,
        "MontantPaye": 3344433.0
      }
    ],
    "UtilisateurCreateurId": 3,
    "DateCreation": "2020-11-03 00:00:00",
    "MontantTotal": 2334432.3,
    "Nom": "3535353",
    "IdGroupe": 16
  }
  
###

HEAD http://localhost:8080/api/Register?courriel=qrosinac@nationalgeographic.com

###
HEAD http://192.168.0.23:44302/api/register?courriel=grosinac@nationalgeographic.com
###

POST http://192.168.0.23:44302/api/factures
Content-Type: application/json

{"DateCreation":"2020-12-12","Id":33,"IdGroupe":0,"UtilisateurCreateurId":10,"MontantTotal":555.0,"PayeursEtMontant":[{"UtilisateurId":10,"MontantPaye":555.0}],"dateFacture":{},"Nom":"Factur","montantPayeParParUtilisateur":{"com.jde.skillbill.donnees.APIRest.entites.UtilisateurRestAPI@1":0.0,"com.jde.skillbill.donnees.APIRest.entites.UtilisateurRestAPI@a":555.0}}


###

POST  http://localhost:8080/api/groupes/11?courriel=qrosinac@nationalgeographic.com
Accept: application/json
###

POST http://192.168.0.23:44302/api/factures
Content-Type: application/json

{"DateCreation":"2020-11-19","Id":0,"IdGroupe":1,"UtilisateurCreateurId":10,"PayeursEtMontant":[{"UtilisateurId":10,"MontantPaye":22.0}],"Photos":[],"Nom":"Facture du 2020-11-19",
  "Photos":[{"LowResEncodeBase64":"ZXdzcmV3cndlcXJ0ZmV3cXRxd2V0ZXc="}]}
###


POST https://localhost:44301/api/factures/2
Content-Type: application/json
###