

POST https://localhost:44301/api/utilisateurs/6/groupes?monnaie=0&nom=testegdfgf
Content-Type: application/xml


###
POST https://localhost:44301/api/utilisateurs/6/groupes?nom=nouveau&monnaie=0

###
PUT https://localhost:44301/api/groupes/1?nom=changed

###
https://localhost:44301/api/utilisateurs/1/groupes/1
Content-Type: application/json

###
POST https://localhost:44301/api/groupes/1?idUtilisateur=2